spring:
  boot:
    admin:
      client:
        url: http://localhost:1111
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 3333
  
msg: welcome to kiran it technology guys.  
        
       
        
